import { PricingPlanType } from "@syncreads/database";

const STARTER_FEATURES = {
  SYNC: "SYNC",
  BROWSER_EXTENSION: "BROWSER_EXTENSION",
  REMARKABLE_INTEGRATION: "REMARKABLE_INTEGRATION",
  KINDLE_INTEGRATION: "KINDLE_INTEGRATION",
  MULTIPLE_FORMATS: "MULTIPLE_FORMATS",
  FEEDS_MANAGEMENT: "FEEDS_MANAGEMENT",
  REALTIME_TRACKING: "REALTIME_TRACKING",
  SIMPLE_ANALYTICS: "SIMPLE_ANALYTICS",
} as const;

const PREMIUM_FEATURES = {
  ...STARTER_FEATURES,
  MORE_FEATURES: "MORE_FEATURES",
} as const;

const UNLIMITED_FEATURES = {
  ...PREMIUM_FEATURES,
  EVEN_MORE_FEATURES: "EVEN_MORE_FEATURES",
} as const;

export const FEATURES = {
  [PricingPlanType.STARTER]: STARTER_FEATURES,
  [PricingPlanType.PREMIUM]: PREMIUM_FEATURES,
  [PricingPlanType.UNLIMITED]: UNLIMITED_FEATURES,
} as const;

export type Feature = keyof typeof FEATURES[PricingPlanType];
