import Head from "next/head";

import { IndexView } from "../views/index/Index";

import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>RSSmarkable</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IndexView />
    </>
  );
};

export default Home;
